### ISSUE TITLE
Add list of urls & output file option

### ISSUE THREAD

**Issue by backd00r101** [Damian89/xssfinder#2]
Hello damian, can't thank you enough for this awesome tool :)

I suggest adding an option to take a list of urls from the user then test them and another option to output the results of the reflected parameters.

Thanks alot!

**Comment by Damian89** [comment]
Hi, 

glad you like it but to be honest: my intention wasnt to make another auto. vuln search tool ;)

But it you may use bash to iterate through a file list and send every url to my tool and then save the output of it using ">" operator ;)
